@startuml builder

hide empty members

class Director {
    +Construct()
}

abstract class Builder {
    +BuildPart()
}

class ConcreteBuilder {
    +BuildPart()
    +GetResult()
}

class Product

Director o--> Builder : builder
ConcreteBuilder --|> Builder
ConcreteBuilder ..> Product

@enduml