@startuml builder

hide empty members

abstract class DataFormat {
    {abstract} +create_root()
    {abstract} +create_key_value()
    {abstract} +create_dict()
    {abstract} +create_list()
}


abstract class RootNode {
    {abstract} +serialize(context)
}

abstract class KeyValueNode {
    {abstract} +serialize(context)
}

abstract class DictNode {
    {abstract} +serialize(context)
}

abstract class ListNode {
    {abstract} +serialize(context)
}

class Client

RootNode --|> DictNode

Client --> DataFormat
Client --> RootNode
Client --> KeyValueNode
Client --> DictNode
Client --> ListNode

@enduml
